<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * EdiItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiItemRepository extends Repository
{
}
