<?php

namespace EdiBundle\Entity;

/**
 * EdiItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiItemRepository extends \Doctrine\ORM\EntityRepository
{
}
