<?php

namespace EdiBundle\Entity;

/**
 * EdiOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
