<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * EdiOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiOrderItemRepository extends Repository
{
}
