<?php

namespace EdiBundle\Entity;

/**
 * EdiOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
