<?php

namespace EdiBundle\Entity;
use AppBundle\Entity\Repository;
/**
 * EdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiRepository extends  Repository
{
}
