<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * EdiruleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiruleRepository extends Repository {
    
}
