<?php

namespace EdiBundle\Entity;

/**
 * EdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdiRepository extends \Doctrine\ORM\EntityRepository
{
}
