<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * EltrekaediRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EltrekaediRepository extends Repository
{
}
