<?php

namespace EdiBundle\Entity;


use AppBundle\Entity\Repository;
/**
 * EltrekaediOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EltrekaediOrderItemRepository extends Repository
{
}
