<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * EltrekaediOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EltrekaediOrderRepository extends Repository {
    
}
