<?php

namespace EdiBundle\Entity;


use AppBundle\Entity\Repository;


/**
 * ViacarediOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViacarediOrderRepository extends Repository
{
}
