<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * ViacarediOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViacarediOrderItemRepository extends Repository
{
}
