<?php

namespace EdiBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * ViacarediRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViacarediRepository extends Repository {
    
}
