services:

    eav_attribute.eav_attribute_creator:
        class: EavBundle\EventListener\EavAttributeCreatorListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
