<?php

namespace SoftoneBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * CustomergroupruleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomergroupruleRepository extends Repository {
}
