<?php
namespace SoftoneBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * CustomergroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomergroupRepository extends Repository {
    
}
