<?php

namespace SoftoneBundle\Entity;

/**
 * CustomerIrsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerIrsRepository extends \Doctrine\ORM\EntityRepository {
    
}
