<?php

namespace SoftoneBundle\Entity;

/**
 * CustomerruleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerruleRepository extends \Doctrine\ORM\EntityRepository
{
}
