<?php

namespace SoftoneBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * InvoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceItemRepository extends Repository {
    
}
