<?php

namespace SoftoneBundle\Entity;

use AppBundle\Entity\Repository;
/**
 * SoftoneProductSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSaleRepository extends Repository
{
}
