<?php

namespace SoftoneBundle\Entity;

use AppBundle\Entity\Entity;

class Softone extends Entity {

    var $authenticateClientID;
    var $loginClientID;
    var $appId = 0;
    var $username = '';
    var $password = '';
    var $requerstUrl = '';

    //var $requerstUrl = 'http://foxnet.oncloud.gr/s1services';


    function __construct() {
        //session_start();
        $this->appId = $this->getSetting("SoftoneBundle:Softone:appId");
        $this->username = $this->getSetting("SoftoneBundle:Softone:username");
        $this->password = $this->getSetting("SoftoneBundle:Softone:password");
        $this->requerstUrl = $this->getSetting("SoftoneBundle:Softone:requerstUrl");

        $loginData = $this->login();
        $this->authenticate($loginData);
    }

    function login() {

        //if ($_SESSION["logindata"]) {
        //print_r($_SESSION["logindata"]);
        //$data = $_SESSION["logindata"];
        //$this->loginClientID = $data->clientID;
        //return $data;  
        //}


        $params = array(
            "service" => "login",
            'username' => $this->username,
            'password' => $this->password,
            'appId' => $this->appId);
        $data = $this->doRequest($params);
        $this->loginClientID = $data->clientID;
        $_SESSION["logindata"] = $data;
        return $data;
    }

    function authenticate($data) {

        //if ($_SESSION["authenticatedata"]) {
        //print_r($_SESSION["authenticatedata"]);
        //  $data = $_SESSION["authenticatedata"];
        // $this->authenticateClientID = $data->clientID;
        // return $data;
        //}


        $this->loginClientID = $data->clientID;
        $params = array(
            "service" => "authenticate",
            "clientID" => $data->clientID,
            "COMPANY" => $data->objs[0]->COMPANY,
            "BRANCH" => $data->objs[0]->BRANCH,
            "MODULE" => $data->objs[0]->MODULE,
            "REFID" => $data->objs[0]->REFID,
                //"USERID": $data->objs->BRANCH,		
        );
        $data = $this->doRequest($params);
        $this->authenticateClientID = $data->clientID;
        $_SESSION["authenticatedata"] = $data;

        return $data;
    }

    function changePassword($new) {
        $params = array(
            "service" => "changePassword",
            "clientID" => $this->authenticateClientID,
            'appId' => $this->appId,
            'OLD' => $this->password,
            'NEW' => $new);
        $data = $this->doRequest($params);
        return $data;
    }

    function getObjects() {
        $params = array(
            "service" => "getObjects",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
        );
        return $this->doRequest($params);
    }

    function getObjectTables($obj) {
        $params = array(
            "service" => "getObjectTables",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
        );
        return $this->doRequest($params);
    }

    function getTableFields($obj, $tbl) {
        $params = array(
            "service" => "getTableFields",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "TABLE" => $tbl,
        );
        return $this->doRequest($params);
    }

    function createSql($params) {
        $params = array(
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => "Items",
            "fSQL" => $params["fSQL"]
        );
        return $this->doRequest($params, $this->requerstUrl . "/JS/SiteData.Items/createSql");
    }

    function createSql2($params) {
        $params = array(
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => "Items",
            "fSQL" => $params["fSQL"]
        );
        return $this->doRequest2($params, $this->requerstUrl . "/JS/SiteData.Items/createSql");
    }

    function doRequest2($data, $requerstUrl = false) {
        $requerstUrl = $requerstUrl ? $requerstUrl : $this->requerstUrl;
        ini_set('memory_limit', '2048M');
        $data_string = json_encode($data);



        $result = file_get_contents($requerstUrl, null, stream_context_create(array(
            'http' => array(
                'method' => 'POST',
                'header' =>
                'Content-Type: application/json' . "\r\n"
                . 'Content-Length: ' . strlen($data_string) . "\r\n",
                'content' => $data_string,
            ),
        )));

        if (@$result1 = gzdecode($result)) {
            $result = iconv("ISO-8859-7", "UTF-8", $result1);
            if (!$result)
                $result = $result1;
        } else {
            $result = iconv("ISO-8859-7", "UTF-8", $result);
            if (!$result)
                $result = $result1;            
        }
        //echo $result;
        $result = '{"success":true,"data":[{"COMPANY":"1","MTRMANFCTR":"1","CODE":"272","NAME":"KAGER","ISACTIVE":"1"},{"COMPANY":"1","MTRMANFCTR":"2","CODE":"4","NAME":"MANN-FILTER","ISACTIVE":"1"},{"COMPANY":"1","MTRMANFCTR":"3","CODE":"G3","NAME":"TEST TEST","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"1","CODE":"2","NAME":"HELLA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"2","CODE":"3","NAME":"ATE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"3","CODE":"4","NAME":"MANN-FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"4","CODE":"6","NAME":"LuK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"5","CODE":"9","NAME":"REINZ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"6","CODE":"11","NAME":"BERU","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"7","CODE":"15","NAME":"NGK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"8","CODE":"16","NAME":"BILSTEIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"9","CODE":"18","NAME":"KONI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"10","CODE":"21","NAME":"VALEO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"11","CODE":"23","NAME":"RUVILLE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"12","CODE":"30","NAME":"BOSCH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"13","CODE":"32","NAME":"SACHS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"14","CODE":"33","NAME":"GATES","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"15","CODE":"37","NAME":"MONROE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"16","CODE":"38","NAME":"PURFLUX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"17","CODE":"39","NAME":"TEXTAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"18","CODE":"43","NAME":"CHAMPION","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"19","CODE":"48","NAME":"JURID","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"20","CODE":"50","NAME":"SKF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"21","CODE":"54","NAME":"FTE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"22","CODE":"55","NAME":"HERTH+BUSS JAKOPARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"23","CODE":"56","NAME":"LOBRO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"24","CODE":"60","NAME":"GOETZE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"25","CODE":"62","NAME":"FERODO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"26","CODE":"66","NAME":"DENSO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"27","CODE":"73","NAME":"MINTEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"28","CODE":"81","NAME":"HENGST FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"29","CODE":"85","NAME":"KYB","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"30","CODE":"86","NAME":"ZIMMERMANN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"31","CODE":"88","NAME":"GLASER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"32","CODE":"89","NAME":"DELPHI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"33","CODE":"95","NAME":"MAGNETI MARELLI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"34","CODE":"101","NAME":"FEBI BILSTEIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"35","CODE":"113","NAME":"PAYEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"36","CODE":"115","NAME":"ULO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"37","CODE":"121","NAME":"METELLI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"38","CODE":"127","NAME":"NK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"39","CODE":"129","NAME":"OPTIMAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"40","CODE":"134","NAME":"MOOG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"41","CODE":"140","NAME":"CORTECO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"42","CODE":"144","NAME":"MEYLE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"43","CODE":"146","NAME":"AMC Filter","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"44","CODE":"153","NAME":"REMSA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"45","CODE":"154","NAME":"DOLZ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"46","CODE":"156","NAME":"JAPANPARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"47","CODE":"158","NAME":"ICER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"48","CODE":"161","NAME":"TRW","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"49","CODE":"166","NAME":"AISIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"50","CODE":"180","NAME":"ALCO FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"51","CODE":"190","NAME":"NATIONAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"52","CODE":"197","NAME":"LPR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"53","CODE":"206","NAME":"A.B.S.","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"54","CODE":"208","NAME":"BIRTH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"55","CODE":"215","NAME":"CALORSTAT by Vernet","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"56","CODE":"218","NAME":"MECAFILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"57","CODE":"220","NAME":"AIRTEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"58","CODE":"237","NAME":"ELWIS ROYAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"59","CODE":"244","NAME":"MEAT & DORIA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"60","CODE":"248","NAME":"NIPPARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"61","CODE":"256","NAME":"FILTRON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"62","CODE":"257","NAME":"ASHIKA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"63","CODE":"260","NAME":"SASIC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"64","CODE":"269","NAME":"STANDARD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"65","CODE":"289","NAME":"BRECO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"66","CODE":"294","NAME":"SACHS (ZF SRE)","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"67","CODE":"295","NAME":"fri.tech.","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"68","CODE":"309","NAME":"E.T.F.","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"69","CODE":"311","NAME":"CIFAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"70","CODE":"312","NAME":"KWP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"71","CODE":"317","NAME":"MALO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"72","CODE":"331","NAME":"ORIGINAL IMPERIUM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"73","CODE":"341","NAME":"HOFFER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"74","CODE":"350","NAME":"BLUE PRINT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"75","CODE":"351","NAME":"AUTOFREN SEINSA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"76","CODE":"356","NAME":"TESLA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"77","CODE":"373","NAME":"GSP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"78","CODE":"381","NAME":"Brake ENGINEERING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"79","CODE":"399","NAME":"EXEDY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"80","CODE":"403","NAME":"MAXGEAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"81","CODE":"409","NAME":"FREMAX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"82","CODE":"410","NAME":"COMMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"83","CODE":"421","NAME":"COMLINE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"84","CODE":"437","NAME":"COOPERSFIAAM FILTERS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"85","CODE":"442","NAME":"ASHUKI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"86","CODE":"445","NAME":"KLARIUS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"87","CODE":"462","NAME":"MFILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"88","CODE":"475","NAME":"BORG & BECK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"89","CODE":"478","NAME":"BGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"90","CODE":"490","NAME":"MULLER FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"91","CODE":"4428","NAME":"KM Germany","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"92","CODE":"4461","NAME":"KAISHIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"93","CODE":"4537","NAME":"APEC braking","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"94","CODE":"4561","NAME":"WESTLAKE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"95","CODE":"4581","NAME":"FLEETGUARD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"96","CODE":"4664","NAME":"Metalcaucho","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"97","CODE":"4703","NAME":"PARTS-MALL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"98","CODE":"4705","NAME":"MOBILETRON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"99","CODE":"4838","NAME":"FI.BA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"100","CODE":"4871","NAME":"COFLE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"101","CODE":"E001","NAME":"FORD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"102","CODE":"E002","NAME":"OPEL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"103","CODE":"E003","NAME":"TOYOTA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"104","CODE":"E004","NAME":"VECTOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"105","CODE":"E005","NAME":"DONALDSON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"106","CODE":"E01","NAME":"FORD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"107","CODE":"E011","NAME":"AFTER MARKET","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"108","CODE":"E012","NAME":"AP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"109","CODE":"E013","NAME":"BAUMANN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"110","CODE":"E014","NAME":"FBS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"111","CODE":"E015","NAME":"PLR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"112","CODE":"E016","NAME":"TRICLO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"113","CODE":"E04","NAME":"VECTOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"114","CODE":"E555","NAME":"555","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"115","CODE":"E999","NAME":"NO NAME","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"116","CODE":"E490","NAME":"SIA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"117","CODE":"E491","NAME":"MAXIMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"118","CODE":"1","NAME":"SPIDAN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"119","CODE":"10","NAME":"ELRING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"120","CODE":"100","NAME":"ROULUNDS RUBBER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"121","CODE":"104","NAME":"ZF LENKSYSTEME","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"122","CODE":"105","NAME":"BEHR HELLA SERVICE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"123","CODE":"106","NAME":"THULE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"124","CODE":"107","NAME":"LETRIKA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"125","CODE":"108","NAME":"TRISCAN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"126","CODE":"109","NAME":"BUGATTI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"127","CODE":"110","NAME":"SNR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"128","CODE":"112","NAME":"EIBACH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"129","CODE":"114","NAME":"BUDWEG CALIPER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"130","CODE":"117","NAME":"LRT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"131","CODE":"118","NAME":"HJS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"132","CODE":"119","NAME":"DELCO REMY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"133","CODE":"12","NAME":"PAGID","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"134","CODE":"122","NAME":"OBERLAND","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"135","CODE":"123","NAME":"NISSENS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"136","CODE":"126","NAME":"STABILUS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"137","CODE":"128","NAME":"BU","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"138","CODE":"13","NAME":"WALKER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"139","CODE":"133","NAME":"MAPCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"140","CODE":"135","NAME":"SIDEM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"141","CODE":"136","NAME":"FONOS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"142","CODE":"137","NAME":"UFI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"143","CODE":"138","NAME":"JOHNS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"144","CODE":"139","NAME":"AJUSA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"145","CODE":"14","NAME":"BOGE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"146","CODE":"141","NAME":"AE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"147","CODE":"142","NAME":"SOFIMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"148","CODE":"143","NAME":"BERGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"149","CODE":"145","NAME":"NWB","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"150","CODE":"151","NAME":"SWAG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"151","CODE":"152","NAME":"ROADHOUSE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"152","CODE":"155","NAME":"URW","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"153","CODE":"157","NAME":"BUGIAD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"154","CODE":"159","NAME":"FACET","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"155","CODE":"162","NAME":"VAICO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"156","CODE":"163","NAME":"CLEAN FILTERS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"157","CODE":"165","NAME":"TWINTEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"158","CODE":"167","NAME":"DUPLI COLOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"159","CODE":"168","NAME":"MOTIP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"160","CODE":"169","NAME":"PRESTO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"161","CODE":"173","NAME":"RAMEDER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"162","CODE":"174","NAME":"QH Benelux","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"163","CODE":"175","NAME":"LESJOFORS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"164","CODE":"176","NAME":"KILEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"165","CODE":"177","NAME":"BTS Turbo","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"166","CODE":"178","NAME":"HEPU","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"167","CODE":"179","NAME":"GOODYEAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"168","CODE":"181","NAME":"GK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"169","CODE":"182","NAME":"SCHLUTTER TURBOLADER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"170","CODE":"183","NAME":"VEMO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"171","CODE":"185","NAME":"KAMOKA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"172","CODE":"186","NAME":"DENCKERMANN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"173","CODE":"187","NAME":"SOMORA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"174","CODE":"188","NAME":"WOLF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"175","CODE":"189","NAME":"CHAMPION LUBRICANTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"176","CODE":"19","NAME":"SWF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"177","CODE":"191","NAME":"IMASAF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"178","CODE":"192","NAME":"FAG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"179","CODE":"193","NAME":"MTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"180","CODE":"194","NAME":"BBT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"181","CODE":"195","NAME":"BREDA LORETT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"182","CODE":"196","NAME":"ALLMAKES","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"183","CODE":"198","NAME":"OCAP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"184","CODE":"199","NAME":"TRUSTING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"185","CODE":"20","NAME":"LUCAS ELECTRICAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"186","CODE":"201","NAME":"KAVO PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"187","CODE":"202","NAME":"GLYCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"188","CODE":"204","NAME":"INA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"189","CODE":"205","NAME":"NRF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"190","CODE":"207","NAME":"CASTROL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"191","CODE":"209","NAME":"TRUCKTEC AUTOMOTIVE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"192","CODE":"210","NAME":"REMKAFLEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"193","CODE":"211","NAME":"BOUGICORD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"194","CODE":"212","NAME":"TUDOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"195","CODE":"216","NAME":"NURAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"196","CODE":"219","NAME":"TIMKEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"197","CODE":"22","NAME":"WABCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"198","CODE":"221","NAME":"ACDelco","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"199","CODE":"222","NAME":"LIQUI MOLY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"200","CODE":"224","NAME":"ERA Benelux","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"201","CODE":"225","NAME":"SCT Germany","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"202","CODE":"226","NAME":"ELSTOCK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"203","CODE":"227","NAME":"TRICO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"204","CODE":"228","NAME":"3F QUALITY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"205","CODE":"232","NAME":"HALDEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"206","CODE":"233","NAME":"DINEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"207","CODE":"234","NAME":"ERA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"208","CODE":"235","NAME":"FRECCIA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"209","CODE":"236","NAME":"FLENNOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"210","CODE":"238","NAME":"IPSA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"211","CODE":"239","NAME":"HUTCHINSON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"212","CODE":"24","NAME":"EXIDE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"213","CODE":"240","NAME":"FAE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"214","CODE":"241","NAME":"FULMEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"215","CODE":"242","NAME":"NECTO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"216","CODE":"243","NAME":"CAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"217","CODE":"245","NAME":"Saleri SIL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"218","CODE":"246","NAME":"EYQUEM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"219","CODE":"247","NAME":"AVA QUALITY COOLING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"220","CODE":"249","NAME":"MGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"221","CODE":"252","NAME":"ZF Parts","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"222","CODE":"253","NAME":"DIEDERICHS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"223","CODE":"254","NAME":"AFA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"224","CODE":"255","NAME":"ECS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"225","CODE":"26","NAME":"VARTA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"226","CODE":"262","NAME":"IPD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"227","CODE":"263","NAME":"SEIM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"228","CODE":"264","NAME":"BERAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"229","CODE":"265","NAME":"ABEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"230","CODE":"266","NAME":"DURON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"231","CODE":"267","NAME":"FAI AutoParts","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"232","CODE":"268","NAME":"JP GROUP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"233","CODE":"27","NAME":"SIDAT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"234","CODE":"271","NAME":"FENOX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"235","CODE":"272","NAME":"KAGER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"236","CODE":"273","NAME":"RECORD FRANCE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"237","CODE":"274","NAME":"AS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"238","CODE":"277","NAME":"AMC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"239","CODE":"278","NAME":"DON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"240","CODE":"279","NAME":"GIRLING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"241","CODE":"28","NAME":"CV PSH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"242","CODE":"281","NAME":"BRECK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"243","CODE":"283","NAME":"AP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"244","CODE":"286","NAME":"KAWE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"245","CODE":"287","NAME":"MAHLE ORIGINAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"246","CODE":"288","NAME":"P.B.R.","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"247","CODE":"29","NAME":"ERNST","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"248","CODE":"290","NAME":"EUROLITES LEART","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"249","CODE":"291","NAME":"PILENGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"250","CODE":"292","NAME":"LIZARTE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"251","CODE":"293","NAME":"LENCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"252","CODE":"296","NAME":"J. DEUS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"253","CODE":"297","NAME":"sbs","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"254","CODE":"298","NAME":"ASSO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"255","CODE":"299","NAME":"WEBASTO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"256","CODE":"300","NAME":"AUTEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"257","CODE":"301","NAME":"TOPRAN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"258","CODE":"302","NAME":"KCW","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"259","CODE":"303","NAME":"WALKER PRODUCTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"260","CODE":"305","NAME":"K&N Filters","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"261","CODE":"306","NAME":"USN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"262","CODE":"31","NAME":"CONTITECH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"263","CODE":"310","NAME":"GRAF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"264","CODE":"313","NAME":"FRIGAIR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"265","CODE":"314","NAME":"PJ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"266","CODE":"316","NAME":"GENERAL RICAMBI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"267","CODE":"318","NAME":"CDX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"268","CODE":"319","NAME":"CALIX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"269","CODE":"320","NAME":"MTE-THOMSON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"270","CODE":"323","NAME":"AUTOMEGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"271","CODE":"324","NAME":"WIX FILTERS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"272","CODE":"325","NAME":"CEF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"273","CODE":"326","NAME":"SCHWITZER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"274","CODE":"327","NAME":"BorgWarner","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"275","CODE":"328","NAME":"3K","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"276","CODE":"329","NAME":"LUOS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"277","CODE":"332","NAME":"DA SILVA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"278","CODE":"336","NAME":"TEMPLIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"279","CODE":"337","NAME":"EUROTEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"280","CODE":"34","NAME":"KNECHT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"281","CODE":"340","NAME":"PRASCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"282","CODE":"342","NAME":"MESSMER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"283","CODE":"345","NAME":"MOTAIR TURBOLADER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"284","CODE":"346","NAME":"TS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"285","CODE":"347","NAME":"TRW Engine Component","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"286","CODE":"349","NAME":"MERITOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"287","CODE":"35","NAME":"LEMFORDER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"288","CODE":"354","NAME":"SIARR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"289","CODE":"355","NAME":"DT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"290","CODE":"357","NAME":"VENEPORTE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"291","CODE":"358","NAME":"MASTER-SPORT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"292","CODE":"36","NAME":"VAN WEZEL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"293","CODE":"360","NAME":"TEAMEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"294","CODE":"361","NAME":"VATOIL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"295","CODE":"362","NAME":"ALKAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"296","CODE":"363","NAME":"CARPRISS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"297","CODE":"364","NAME":"UNIFLUX FILTERS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"298","CODE":"366","NAME":"WOKING","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"299","CODE":"367","NAME":"FA1","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"300","CODE":"368","NAME":"GGT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"301","CODE":"371","NAME":"DEPA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"302","CODE":"372","NAME":"CAMPRO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"303","CODE":"374","NAME":"ACI - AVESA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"304","CODE":"375","NAME":"SONNAK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"305","CODE":"376","NAME":"CENTRA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"306","CODE":"377","NAME":"BOSCH DIAGNOSTICS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"307","CODE":"378","NAME":"OPEN PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"308","CODE":"379","NAME":"AQUAPLUS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"309","CODE":"380","NAME":"FRENKIT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"310","CODE":"382","NAME":"TURBO S HOET","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"311","CODE":"383","NAME":"ANGLI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"312","CODE":"385","NAME":"GOETZE ENGINE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"313","CODE":"386","NAME":"GLO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"314","CODE":"387","NAME":"KLAXCAR FRANCE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"315","CODE":"388","NAME":"MOTORAD","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"316","CODE":"389","NAME":"GLYSANTIN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"317","CODE":"390","NAME":"SUPLEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"318","CODE":"391","NAME":"EAI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"319","CODE":"393","NAME":"CEVAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"320","CODE":"394","NAME":"BARUM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"321","CODE":"396","NAME":"PRESTOLITE ELECTRIC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"322","CODE":"397","NAME":"JANMOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"323","CODE":"398","NAME":"EUROL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"324","CODE":"400","NAME":"RAICAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"325","CODE":"405","NAME":"CAUTEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"326","CODE":"406","NAME":"BM CATALYSTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"327","CODE":"407","NAME":"FIRST LINE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"328","CODE":"408","NAME":"SNRA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"329","CODE":"41","NAME":"BOSAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"330","CODE":"411","NAME":"EUROCABLE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"331","CODE":"412","NAME":"ATL Autotechnik","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"332","CODE":"415","NAME":"FENNO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"333","CODE":"419","NAME":"PERFECT CIRCLE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"334","CODE":"42","NAME":"DAYCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"335","CODE":"423","NAME":"LUCAS DIESEL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"336","CODE":"424","NAME":"LUCAS ENGINE DRIVE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"337","CODE":"425","NAME":"HC-PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"338","CODE":"426","NAME":"MONOFLEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"339","CODE":"427","NAME":"ASMET","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"340","CODE":"429","NAME":"WAT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"341","CODE":"430","NAME":"RTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"342","CODE":"431","NAME":"SERCORE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"343","CODE":"432","NAME":"KOLBENSCHMIDT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"344","CODE":"433","NAME":"STATIM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"345","CODE":"434","NAME":"DETA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"346","CODE":"435","NAME":"EQUAL QUALITY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"347","CODE":"4357","NAME":"DIVINOL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"348","CODE":"436","NAME":"MOTUL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"349","CODE":"438","NAME":"STOP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"350","CODE":"44","NAME":"PUROLATOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"351","CODE":"440","NAME":"NPS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"352","CODE":"441","NAME":"FISPA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"353","CODE":"4425","NAME":"VEMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"354","CODE":"4426","NAME":"ABE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"355","CODE":"4427","NAME":"Magnum Technology","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"356","CODE":"443","NAME":"ENERGIZER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"357","CODE":"4449","NAME":"MOBIL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"358","CODE":"4451","NAME":"YUASA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"359","CODE":"4452","NAME":"GS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"360","CODE":"4455","NAME":"BSG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"361","CODE":"446","NAME":"SK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"362","CODE":"4462","NAME":"KM International","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"363","CODE":"4463","NAME":"CALIBER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"364","CODE":"4464","NAME":"AUTOTEAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"365","CODE":"4466","NAME":"THERMOTEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"366","CODE":"4467","NAME":"FORTUNE LINE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"367","CODE":"4468","NAME":"YAMATO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"368","CODE":"447","NAME":"PILKINGTON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"369","CODE":"4470","NAME":"MISFAT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"370","CODE":"448","NAME":"UNICO FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"371","CODE":"4481","NAME":"CARBOX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"372","CODE":"449","NAME":"HUCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"373","CODE":"4495","NAME":"AUGER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"374","CODE":"4496","NAME":"LAUBER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"375","CODE":"4498","NAME":"WAGNER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"376","CODE":"45","NAME":"SPAHN GLUHLAMPEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"377","CODE":"450","NAME":"RPK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"378","CODE":"4503","NAME":"SAUER-WERKZEUG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"379","CODE":"4504","NAME":"AINDE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"380","CODE":"4505","NAME":"PHIRA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"381","CODE":"4512","NAME":"ERT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"382","CODE":"4514","NAME":"ET ENGINETEAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"383","CODE":"4519","NAME":"DJ PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"384","CODE":"4520","NAME":"PROTECHNIC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"385","CODE":"4522","NAME":"KOSHIMO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"386","CODE":"4523","NAME":"HIDRIA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"387","CODE":"4527","NAME":"AIR FREN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"388","CODE":"4528","NAME":"AD KUHNER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"389","CODE":"454","NAME":"BANDO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"390","CODE":"4543","NAME":"PowerMax","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"391","CODE":"4546","NAME":"KRAFT AUTOMOTIVE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"392","CODE":"4548","NAME":"LIPE CLUTCH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"393","CODE":"455","NAME":"SIGAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"394","CODE":"4555","NAME":"BLIC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"395","CODE":"4558","NAME":"PATRON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"396","CODE":"4559","NAME":"MECARM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"397","CODE":"456","NAME":"VILLAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"398","CODE":"4567","NAME":"EATON","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"399","CODE":"4569","NAME":"RANCHO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"400","CODE":"457","NAME":"EDR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"401","CODE":"4570","NAME":"MAYSAN MANDO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"402","CODE":"4572","NAME":"MAURICE LECOY","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"403","CODE":"4573","NAME":"ROSTAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"404","CODE":"4576","NAME":"ASAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"405","CODE":"4578","NAME":"BRT Bearings","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"406","CODE":"4579","NAME":"Automotive Bearings","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"407","CODE":"4582","NAME":"SPJ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"408","CODE":"4583","NAME":"CARRAB BRAKE PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"409","CODE":"4585","NAME":"DOGA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"410","CODE":"459","NAME":"IPS Parts","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"411","CODE":"4592","NAME":"SANDO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"412","CODE":"4595","NAME":"STELLOX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"413","CODE":"4596","NAME":"SAFA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"414","CODE":"4597","NAME":"XADO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"415","CODE":"4598","NAME":"3RG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"416","CODE":"460","NAME":"DRI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"417","CODE":"4600","NAME":"LYNXauto","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"418","CODE":"4603","NAME":"ELECTRIC LIFE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"419","CODE":"4604","NAME":"CASALS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"420","CODE":"4606","NAME":"NAGARES","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"421","CODE":"4607","NAME":"SHAFTEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"422","CODE":"4609","NAME":"ROTA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"423","CODE":"461","NAME":"RAVENOL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"424","CODE":"4610","NAME":"BEGEL Germany","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"425","CODE":"4613","NAME":"DEEZA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"426","CODE":"4614","NAME":"SEM LASTIK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"427","CODE":"4615","NAME":"GARRETT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"428","CODE":"4620","NAME":"UNIPOINT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"429","CODE":"4622","NAME":"MSG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"430","CODE":"4623","NAME":"SAMPA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"431","CODE":"4624","NAME":"MD Rebuilt","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"432","CODE":"4625","NAME":"HELLA PAGID","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"433","CODE":"4627","NAME":"WAIglobal","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"434","CODE":"4628","NAME":"ATI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"435","CODE":"4630","NAME":"SAKURA Automotive","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"436","CODE":"4631","NAME":"ASVA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"437","CODE":"4634","NAME":"ROSI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"438","CODE":"4651","NAME":"AUTOKIT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"439","CODE":"4652","NAME":"PEMEBLA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"440","CODE":"4653","NAME":"ODM-MULTIPARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"441","CODE":"4654","NAME":"ACR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"442","CODE":"4655","NAME":"PROCODIS FRANCE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"443","CODE":"4656","NAME":"AUTOCLIMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"444","CODE":"4657","NAME":"LORO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"445","CODE":"4658","NAME":"MABY PARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"446","CODE":"4659","NAME":"FIL FILTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"447","CODE":"466","NAME":"SIMER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"448","CODE":"4662","NAME":"HUF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"449","CODE":"4667","NAME":"STC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"450","CODE":"467","NAME":"CS Germany","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"451","CODE":"4670","NAME":"BERGKRAFT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"452","CODE":"4671","NAME":"NEOLUX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"453","CODE":"4673","NAME":"VPM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"454","CODE":"4675","NAME":"STARLINE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"455","CODE":"4676","NAME":"ROTINGER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"456","CODE":"4678","NAME":"COBREQ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"457","CODE":"468","NAME":"DONMEZ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"458","CODE":"4680","NAME":"SPILU","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"459","CODE":"4683","NAME":"OSSCA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"460","CODE":"4686","NAME":"PROFIT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"461","CODE":"4688","NAME":"AUTOGAMMA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"462","CODE":"4689","NAME":"JC PREMIUM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"463","CODE":"4690","NAME":"PASCAL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"464","CODE":"4691","NAME":"KANACO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"465","CODE":"4692","NAME":"YAZUKA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"466","CODE":"4693","NAME":"BTA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"467","CODE":"4694","NAME":"NEXUS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"468","CODE":"4696","NAME":"PACOL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"469","CODE":"4697","NAME":"PNEUMATICS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"470","CODE":"4698","NAME":"S-TR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"471","CODE":"4699","NAME":"SBP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"472","CODE":"47","NAME":"BREMI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"473","CODE":"470","NAME":"MAPA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"474","CODE":"4700","NAME":"TRUCK TEQ","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"475","CODE":"4701","NAME":"TRUCKLIGHT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"476","CODE":"4702","NAME":"BOSS FILTERS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"477","CODE":"4707","NAME":"LUZAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"478","CODE":"4708","NAME":"RIW","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"479","CODE":"471","NAME":"DITAS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"480","CODE":"4718","NAME":"KRAFTTECH","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"481","CODE":"472","NAME":"SAMI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"482","CODE":"4722","NAME":"HELLA NUSSBAUM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"483","CODE":"4725","NAME":"ELECTRO AUTO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"484","CODE":"4727","NAME":"FORMPART","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"485","CODE":"473","NAME":"CABOR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"486","CODE":"474","NAME":"MONT BLANC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"487","CODE":"476","NAME":"AUTO AIR GLOUCESTER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"488","CODE":"479","NAME":"ALANKO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"489","CODE":"481","NAME":"JAPKO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"490","CODE":"482","NAME":"WEEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"491","CODE":"484","NAME":"CASCO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"492","CODE":"485","NAME":"NARVA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"493","CODE":"486","NAME":"FRAP","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"494","CODE":"487","NAME":"AP Automotive Prod.","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"495","CODE":"488","NAME":"EEC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"496","CODE":"49","NAME":"BENDIX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"497","CODE":"492","NAME":"RCA FRANCE","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"498","CODE":"493","NAME":"TRUCKTECHNIC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"499","CODE":"494","NAME":"BRISK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"500","CODE":"495","NAME":"COJALI","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"501","CODE":"497","NAME":"CX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"502","CODE":"499","NAME":"ZAFFO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"503","CODE":"5","NAME":"PIERBURG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"504","CODE":"500","NAME":"GALFER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"505","CODE":"51","NAME":"WESTFALIA","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"506","CODE":"52","NAME":"BEHR THERMOT-TRONIK","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"507","CODE":"57","NAME":"QUINTON HAZELL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"508","CODE":"58","NAME":"EKG","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"509","CODE":"59","NAME":"FRAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"510","CODE":"61","NAME":"TYC","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"511","CODE":"63","NAME":"PE Automotive","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"512","CODE":"64","NAME":"OPTIBELT","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"513","CODE":"65","NAME":"BREMBO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"514","CODE":"67","NAME":"OSRAM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"515","CODE":"68","NAME":"ZF","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"516","CODE":"7","NAME":"EBERSPACHER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"517","CODE":"71","NAME":"GABRIEL","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"518","CODE":"72","NAME":"HERTH+BUSS ELPARTS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"519","CODE":"75","NAME":"PHILIPS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"520","CODE":"76","NAME":"PEX","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"521","CODE":"78","NAME":"KLOKKERHOLM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"522","CODE":"79","NAME":"WAHLER","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"523","CODE":"80","NAME":"AKS DASIS","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"524","CODE":"83","NAME":"VDO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"525","CODE":"87","NAME":"FRIESEN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"526","CODE":"90","NAME":"FARCOM","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"527","CODE":"91","NAME":"TECNOCAR","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"528","CODE":"92","NAME":"SogefiPro","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"529","CODE":"93","NAME":"SCHLIECKMANN","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"530","CODE":"96","NAME":"AL-KO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"531","CODE":"97","NAME":"WAECO","ISACTIVE":"1"},{"COMPANY":"1000","MTRMANFCTR":"532","CODE":"T","NAME":"METZGER","ISACTIVE":"1"}]}';
        print_r(json_decode($result));
        
        return json_decode($result);
    }

    function getCustomItems($params) {
        $params = array(
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => "Items",
            "DateL" => $params["DateL"],
            "DateH" => $params["DateH"]
        );
        return $this->doRequest($params, $this->requerstUrl . "/JS/SiteData.Items/getItems");
    }

    function getCustomerAddresses($params = false) {
        $params = array(
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => "Items",
            "DateL" => $params["DateL"],
            "DateH" => $params["DateH"]
        );
        return $this->doRequest($params, $this->requerstUrl . "/JS/SiteData.Items/getAddresses");
    }

    function getDialog($obj, $list = "") {
        $params = array(
            "service" => "getDialog",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "LIST" => $list,
        );
        return $this->doRequest($params);
    }

    function getFormDesign($form = "") {
        $params = array(
            "service" => "getFormDesign",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "FORM" => $form,
        );
        return $this->doRequest($params);
    }

    function getBrowserInfo($obj, $list = "", $filters = "") {
        $params = array(
            "service" => "getBrowserInfo",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "LIST" => $list,
            "FILTERS" => $filters,
        );
        //print_r($params);
        return $this->doRequest($params);
    }

    function getBrowserData($data) {
        $params = array(
            "service" => "getBrowserData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "reqID" => $data->reqID,
            "START" => 0,
            "LIMIT" => 70000000
        );
        $out = $this->doRequest($params);
        return $out;
    }

    function getBrowser($obj, $list = "", $filters = "") {
        $browserInfo = $this->getBrowserInfo($obj, $list, $filters);
        return $this->getBrowserData($browserInfo);
    }

    function getReportInfo($obj) {
        $params = array(
            "service" => "getReportInfo",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "LIST" => "",
            "FILTERS" => "",
        );

        return $this->doRequest($params);
    }

    function getReportData($data, $pagenum = 1) {
        $params = array(
            "service" => "getReportData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "reqID" => $data->reqID,
            "PAGENUM" => $pagenum
        );
        return $this->doRequest($params);
    }

    function getReport($obj, $pagenum = 1) {
        $reportInfo = $this->getReportInfo($obj);
        return getReportData($reportInfo, $pagenum = 1);
    }

    function getData($obj, $key, $form = "", $locateinfo = "") {
        $params = array(
            "service" => "getData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "FORM" => $form,
            "KEY" => $key,
            "LOCATEINFO" => $locateinfo
        );
        return $this->doRequest($params);
    }

    function setData($data, $obj, $key = "") {
        $params = array(
            "service" => "setData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "KEY" => $key,
            "data" => $data
        );
        //echo json_encode($params);
        return $this->doRequest($params);
    }

    function calculate($data, $obj, $form = "", $key = "", $locateinfo = "ASSLINES:ASDCODE,DISC1PRC,LINENUM,LINEVAL,MTRL,MTRL_ASSET_CODE,MTRL_ASSET_NAME,NAME,PRICE,QTY1,VAT;ITELINES:DISC1PRC,LINENUM,LINEVAL,MTRL,MTRL_ITEM_CODE,MTRL_ITEM_CODE1,MTRL_ITEM_CODE2,MTRL_ITEM_NAME,MTRL_ITEM_NAME1,PRICE,QTY1;MTRDOC:QTY;SALDOC:BUSUNITS,CMPFINCODE,COMMENTS1,DISC1PRC,DISC1VAL,DISC2PRC,EXPN,FINDOC,FINDOC_SALMTRDOC_FINDOC,FINDOC_SALMTRDOC_WHOUSE,FINSTATES,NETAMNT,PAYMENT,PRJC,PRJC_PRJC_CODE,PRJC_PRJC_NAME,REMARKS,SALESMAN,SALESMAN_PRSNIN_CODE,SALESMAN_PRSNIN_NAME,SALESMAN_PRSNIN_NAME2,SERIES,SUMAMNT,TRDBRANCH,TRDBRANCH_TRDBRANCH_CODE,TRDBRANCH_TRDBRANCH_NAME,TRDR,TRDR_CUSTOMER_AFM,TRDR_CUSTOMER_CODE,TRDR_CUSTOMER_NAME,TRNDATE,VATAMNT;SRVLINES:DISC1PRC,LINENUM,LINEVAL,MTRL,MTRL_SERVICE_CODE,MTRL_SERVICE_NAME,MTRTYPE,PRICE,QTY1,VAT") {
        $params = array(
            "service" => "calculate",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "FORM" => $form,
            "KEY" => $key,
            "LOCATEINFO" => $locateinfo,
            "data" => $data
        );
        return $this->doRequest($params);
    }

    function delData($obj, $key, $form = "") {
        $params = array(
            "service" => "delData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => $obj,
            "FORM" => $form,
            "KEY" => $key,
        );
        return $this->doRequest($params);
    }

    function getSelectorData($editor = "", $value = "") {
        $params = array(
            "service" => "delData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "EDITOR" => $editor,
            "VALUE" => $value
        );
        return $this->doRequest($params);
    }

    function selectorFields($tbl, $keyname, $keyvalue, $fields) {
        $params = array(
            "service" => "delData",
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "TABLENAME" => $tbl,
            "KEYNAME" => $keyname,
            "KEYVALUE" => $keyvalue,
            "RESULTFIELDS" => $fields
        );
        return $this->doRequest($params);
    }

    function doRequest($data, $requerstUrl = false) {
        $requerstUrl = $requerstUrl ? $requerstUrl : $this->requerstUrl;
        ini_set('memory_limit', '2048M');
        $data_string = json_encode($data);



        $result = file_get_contents($requerstUrl, null, stream_context_create(array(
            'http' => array(
                'method' => 'POST',
                'header' =>
                'Content-Type: application/json' . "\r\n"
                . 'Content-Length: ' . strlen($data_string) . "\r\n",
                'content' => $data_string,
            ),
        )));
        if (@$result1 = gzdecode($result)) {
            $result = iconv("ISO-8859-7", "UTF-8", $result1);
        } else {
            $result = iconv("ISO-8859-7", "UTF-8", $result);
        }
        $result = str_replace("	", "", $result);
        return json_decode($result);
    }

    function getManufactures($params = array()) {
        $params = array(
            "clientID" => $this->authenticateClientID,
            "appId" => $this->appId,
            "OBJECT" => "Items",
            "DateL" => $params["DateL"],
            "DateH" => $params["DateH"]
        );
        //return $this->doRequest($params, "http://bsautospare.oncloud.gr/s1services/JS/SiteData.Items/getManufactures");
        $requerstUrl = $this->requerstUrl . "/JS/SiteData.Items/getManufactures";
        ini_set('memory_limit', '2048M');
        $data_string = json_encode($params);

        $result = @file_get_contents($requerstUrl, null, stream_context_create(array(
                    'http' => array(
                        'method' => 'POST',
                        'header' =>
                        'Content-Type: application/json' . "\r\n"
                        . 'Content-Length: ' . strlen($data_string) . "\r\n",
                        'content' => $data_string,
                    ),
        )));

        if (@$result1 = gzdecode($result)) {
            //$result = iconv("ISO-8859-7", "UTF-8", $result1);
            $result = $result1;
        } else {
            //$result = iconv("ISO-8859-7", "UTF-8", $result);
            $result = $result;
        }
        $result = iconv("WINDOWS-1252", "UTF-8", $result);
        return json_decode($result);
    }

    function retrieveColumns($obj, $list = "") {
        $result = $this->getBrowserInfo($obj, $list);
        $out = array();
        foreach ($result->columns as $column) {
            //if ($i++ > 1) {
            $out[str_replace(".", "_", strtolower($column->dataIndex))] = $column->header;
            //}
        }
        return $out;
    }

    function retrieveFields($obj, $list = "", $filters = "") {
        $result = $this->getBrowserInfo($obj, $list, $filters);
        $out = array();
        foreach ($result->fields as $field) {
            //if ($i++ > 1) {
            $out[] = str_replace(".", "_", strtolower($field->name));
            //}
        }
        return $out;
    }

    function retrieveData($obj, $list = "", $filters = "") {
        $fields = $this->getBrowserInfo($obj, $list, $filters);
        foreach ((array) $fields->fields as $key => $field) {
            $fieldRow[$key] = str_replace(".", "_", strtolower($field->name));
        }
        $datas = $this->getBrowser($obj, $list, $filters);
        //print_r($datas);
        $retrievedDataTable = array();
        foreach ((array) $datas->rows as $row) {
            $retrievedDataRow = array();
            foreach ($row as $key => $data_field) {
                $retrievedDataRow[$fieldRow[$key]] = $data_field;
            }
            $retrievedDataTable[] = $retrievedDataRow;
        }
        return $retrievedDataTable;
    }

}
