<?php

namespace SoftoneBundle\Entity;

/**
 * SoftoneProductSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftoneProductSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
