access:
    resource: "@AccessBundle/Resources/config/routing.yml"
    prefix:   /

attribute:
    resource: "@EavBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@PartsboxBundle/Controller/"
    type:     annotation
