<?php

namespace MegasoftBundle\Entity;

/**
 * CustomergroupruleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomergroupruleRepository extends \Doctrine\ORM\EntityRepository
{
}
