<?php

namespace MegasoftBundle\Entity;

/**
 * CustomergroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomergroupRepository extends \Doctrine\ORM\EntityRepository
{
}
