<?php

namespace MegasoftBundle\Entity;

/**
 * OrderitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderitemRepository extends \Doctrine\ORM\EntityRepository
{
}
