<?php

namespace MegasoftBundle\Entity;

use AppBundle\Entity\Repository;

/**
 * MegasoftBundleProductSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSaleRepository extends Repository {
    
}
